config/routes.rb
Rails.application.routes.draw do
  get 'productos/index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :marcas
  resources :productos

  root 'inicio#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/marca.rb
class Marca < ApplicationRecord
	validates :nombre, presence: true, length:{ minimum: 8}, uniqueness: true
end

app/models/producto.rb
class Producto < ApplicationRecord
	validates :nombre, presence: true, length:{ minimum: 8}, uniqueness: true
	validates :marca, presence: true
	validates :descripcion, presence: true, length:{ minimum: 10, maximum: 300}
	validates :precio, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/inicio_controller.rb
class InicioController < ApplicationController
  def index
  end
end

app/controllers/marcas_controller.rb
class MarcasController < ApplicationController
  
  def index
  	@marcas = Marca.all
  end

  def show
  	@marca = Marca.find(params[:id])
  end

  def new
  	@marca = Marca.new
  end

  def create
  	@marca = Marca.create(nombre: params[:marca][:nombre])
  	
  	if @marca.save
  		redirect_to marcas_path
  	else 
  		render :new
  	end
  end

  def destroy
  	@marca = Marca.find(params[:id])
  	@marca.destroy
  	redirect_to marcas_path
  end

  def update
  	@marca = Marca.find(params[:id])

  	if @marca.update(nombre: params[:marca][:nombre])
  		redirect_to marcas_path
  	else 
  		render :edit
  	end
  end

  def edit
  	@marca = Marca.find(params[:id])
  end

end

app/controllers/productos_controller.rb
class ProductosController < ApplicationController
  
  def index
  	@productos = Producto.all
  end

  def show
  	@producto = Producto.find(params[:id])
  end

  def new
  	@producto = Producto.new
  end

  def create
  	@producto = Producto.create(
      nombre: params[:producto][:nombre], 
      marca: params[:producto][:marca],
      descripcion: params[:producto][:descripcion],
      precio: params[:producto][:precio])

  	if @producto.save
  		redirect_to productos_path
  	else 
  		render :new
  	end
  end

  def destroy
  	@producto = Producto.find(params[:id])
  	@producto.destroy
  	redirect_to productos_path
  end

  def update
  	@producto = Producto.find(params[:id])

  	if @producto.update(
      nombre: params[:producto][:nombre], 
      marca: params[:producto][:marca],
      descripcion: params[:producto][:descripcion],
      precio: params[:producto][:precio])
  		redirect_to productos_path
  	else 
  		render :edit
  	end
  end

  def edit
  	@producto = Producto.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/inicio_helper.rb
module InicioHelper
end

app/views/inicio/index.html.erb
<section class="jumbotron text-center">
  <div class="container">
    <h1 class="jumbotron-heading">Mi Primer proyecto RoR</h1>
    <p class="lead text-muted">Este fue mi primer proyecto RoR, realmente me gusto la forma en que se estructuran las cosas, algunas ya tenia la noción gracias a que he usado Grails and Groovy, pero me agrado Rails on Ruby.</p>
    <p>
      <a href="#" class="btn btn-primary">Main call to action</a>
      <a href="#" class="btn btn-secondary">Secondary action</a>
    </p>
  </div>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Mi primer RoR</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet">
  </head>
  <body>
	<nav class="navbar navbar-default">
	  <div class="container-fluid">
	    <div class="navbar-header">
	      <%= link_to "@dgarcia", { :controller => :inicio, :action => :index }, class:"navbar-brand"%>
	    </div>
	    <ul class="nav navbar-nav">
	      <li class="<%= 'active' if current_page? controller: :marcas, action: :index %>">
	      	<%= link_to "Marcas", { :controller => :marcas, :action => :index }%>
	      </li>
	      <li class="<%= 'active' if current_page? controller: :productos, action: :index %>">
	      	<%= link_to "Productos", { :controller => :productos, :action => :index }%>
	      </li>
	    </ul>
	  </div>
	</nav>
	<div class="container">
    	<%= yield %>
	</div>
	<footer class="footer">
      <div align="center" class="container">
        <span class="text-muted">Versió 0.0.1</span>
      </div>
    </footer>
  </body>
</html>

app/views/marcas/_form.html.erb
<div class="page-header" align="center">
	<h3> <%= nombre%> Marca</h3>
</div>
<%= form_for(@marca, html: {class: "form-horizontal"}) do |f| %>
	<div class="form-group">
		<label class="control-label col-sm-1" for="nombre">Nombre:</label>
		<div class="col-sm-5">
			<%= f.text_field :nombre, placeholder: "Nombre de la marca", class: "form-control"%>
		</div>
	</div>
	<div class="form-group">
		<div class="col-sm-12" align="right">
      		<%= f.submit "Guardar", class:"btn btn-primary"%>
      		<%= link_to "Volver", { :controller => :marcas, :action => :index }, class:"btn btn-primary"%>
      	</div>
    </div>
    <div class="form-group">
    	<div class="col-sm-12">
		    <% @marca.errors.full_messages.each do |message|%>
				<div class="alert alert-danger">
				  <strong>¡Error!</strong> <%= message%>
				</div>
		    <%end%>
		</div>
	</div>
<%end%>

app/views/marcas/edit.html.erb
<%= render 'form', nombre:"Editar"%>

app/views/marcas/index.html.erb
<div class="page-header">
	<h3 align="center"> Consultar Marcas</h3>
</div>
<div align="right">
	<%= link_to "Crear Marca", { :controller => :marcas, :action => :new }, {class:"btn btn-primary"}%>
</div>
<table class="table table-striped">
	<thead>
		<tr>
			<th>Marca</th>
			<th class="text-center"><b>Acciones</b></th>
		</tr>
	</thead>
	<tbody>
		<% @marcas.each do |marca|%>
			<tr>
				<td>
					<%= marca.nombre %>
				</td>
				<td class="text-center">
					<%= link_to edit_marca_path(Marca.find(marca.id)), class:"btn btn-small btn-primary" do %>
					    <span class="glyphicon glyphicon-pencil"></span>
					<% end %>
					<%= link_to marca, method: :delete, data:{confirm:"¿Desea eliminar la marca?"}, class:"btn btn-small btn-danger" do %>
					    <span class="glyphicon glyphicon-trash"></span>
					<% end %>
				</td>
			</tr>
		<%end%>
	</tbody>
</table>

app/views/marcas/new.html.erb
<%= render 'form', nombre:"Editar"%>

app/views/marcas/show.html.erb
<h1><%= @marca.nombre %></h1>
<%= link_to "Editar", edit_marca_path(@marca)%>

app/views/productos/_form.html.erb
<div class="page-header" align="center">
	<h3> <%= nombre%> Producto</h3>
</div>
<%= form_for(@producto, html: {class: "form-horizontal"}) do |f| %>
	<div class="form-group">
		<label class="control-label col-sm-1" for="nombre">Nombre:</label>
		<div class="col-sm-5">
			<%= f.text_field :nombre, placeholder: "Nombre del producto", class: "form-control"%>
		</div>
	</div>
	<div class="form-group">
		<label class="control-label col-sm-1" for="marca">Marca:</label>
		<div class="col-sm-5">
			<%= f.select :marca, options_for_select(Marca.all.map{ |c| [c.nombre, c.id]}, @producto.marca), {:include_blank => 'Seleccione una marca'}, { :class => 'form-control' } %>

		</div>
	</div>
	<div class="form-group">
		<label class="control-label col-sm-1" for="descripcion">Descripción:</label>
		<div class="col-sm-5">
			<%= f.text_area :descripcion, placeholder: "Descripción del producto", class: "form-control", cols: "30", rows: "10"%>
		</div>
	</div>
	<div class="form-group">
		<label class="control-label col-sm-1" for="descripcion">Precio:</label>
		<div class="col-sm-5">
			<%= f.number_field :precio, placeholder: "Precio del producto", class: "form-control", :step => 0.01 %>
		</div>
	</div>
	<div class="form-group">
		<div class="col-sm-12" align="right">
      		<%= f.submit "Guardar", class:"btn btn-primary"%>
      		<%= link_to "Volver", { :controller => :productos, :action => :index }, class:"btn btn-primary"%>
      	</div>
    </div>
    <div class="form-group">
    	<div class="col-sm-12">
		    <% @producto.errors.full_messages.each do |message|%>
				<div class="alert alert-danger">
				  <strong>¡Error!</strong> <%= message%>
				</div>
		    <%end%>
		</div>
	</div>
<%end%>

app/views/productos/edit.html.erb
<%= render 'form', nombre:"Editar"%>

app/views/productos/index.html.erb
<div class="page-header">
	<h3 align="center"> Consultar Productos</h3>
</div>
<div align="right">
	<%= link_to "Crear Producto", { :controller => :productos, :action => :new }, {class:"btn btn-primary"}%>
</div>
<table class="table table-striped">
	<thead>
		<tr>
			<th>Nombre</th>
			<th>Marca</th>
			<th>Descripción</th>
			<th>Precio</th>
			<th class="text-center"><b>Acciones</b></th>
		</tr>
	</thead>
	<tbody>
		<% @productos.each do |producto|%>
			<tr>
				<td>
					<%= producto.nombre %>
				</td>
				<td>
					<%= Marca.find(producto.marca).nombre %>
				</td>
				<td>
					<%= producto.descripcion %>
				</td>
				<td>
					$ <%= producto.precio %>
				</td>
				<td class="text-center">
					<%= link_to edit_producto_path(Producto.find(producto.id)), class:"btn btn-small btn-primary" do %>
					    <span class="glyphicon glyphicon-pencil"></span>
					<% end %>
					<%= link_to producto, method: :delete, data:{confirm:"¿Desea eliminar el producto?"}, class:"btn btn-small btn-danger" do %>
					    <span class="glyphicon glyphicon-trash"></span>
					<% end %>
				</td>
			</tr>
		<%end%>
	</tbody>
</table>

app/views/productos/new.html.erb
<%= render 'form', nombre:"Nuevo"%>

app/views/productos/show.html.erb
<h1><%= @marca.nombre %></h1>
<%= link_to "Editar", edit_marca_path(@marca)%>